### ISSUE TITLE
Zniekształcone obrazki

### ISSUE THREAD

**Issue by azzarro7** [azzarro7/POS#1]
Przy sklejaniu obrazków innych niż kwadratowe, wychodzą one nienaturalnie rozciągnięte. Funkcję trzeba zmodyfikować, tak by obliczała aspect ratio obrazków i tą informacje wykorzystywała przy sklejaniu, zamiast rozwiązania na sztywno tak jak jest teraz.

**Comment by anjasz** [comment]
Poprawiłem funkcję sklejającą obrazki. Szerokość miniaturki obliczana jest na podstawie ilości kolumn, natomiast wysokość jest dobierana dla każdego obrazka z osobna na podstawie jego aspect ratio(zmienna ratio). Współrzędna y, przy łączeniu miniatur, jest liczona dla najwyższej miniaturki, stąd pomiędzy obrazkami są przerwy.
