### ISSUE TITLE
sklejanie: liczba kolumn i wierszy

### ISSUE THREAD

**Issue by azzarro7** [azzarro7/POS#2]
Liczba kolumn i wierszy powinna być obliczana na podstawie wymiarów przeskalowanych obrazków, oraz ilości obrazków zamiast rozwiązania na sztywno.

**Comment by anjasz** [comment]
Poprawiłem obliczanie liczby kolumn i wierszy. Program dodaje teraz kolejne wiersze jeżeli liczba obrazków przekroczy 2. Przy 3 obrazkach które aktualnie wczytujemy wygląda to tak, że 2 pierwsze znajdują się w pierwszym wierszu, trzeci w drugim.
